apiVersion: apps/v1
kind: Deployment
metadata:
  name: vueapp # Set the name of the deployment
spec: 
  selector:
    matchLabels:
      app: vueapp
  replicas: 2 # Set the number of pods
  template: 
    metadata:
      labels: 
        app: vueapp
    spec:
      containers:
      - name: vueapp # Sets the container name
        image: sshector294/vueapp:2 # Sets the container image
        ports:
        - containerPort: 8000 # Exposes container port
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: vueapp-service # Set the name of the service
# spec:
#   selector:
#     app: vueapp
#   ports:
#   - port: 8000 # Set the service port
#     protocol: TCP
#     targetPort: 80 # Set the service target port
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: vueapp

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   labels:
#     app: vue-app
#   name: vue-app
# spec: 
#   replicas: 3
#   selector:
#     matchLabels:
#       app: vue-app
#   strategy: {}
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: vue-app
#     spec:
#       containers:
#       - image: sshector294/vueapp:2
#         name: vue-app
#         resources: {}
# status: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: lb-service
#   labels:
#     app: lb-service
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 5000
#   selector:
#     app: vue-app
