apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vue-app
  name: vue-app
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: vue-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vue-app
    spec:
      containers:
      - image: sshector294/vueapp:2
        name: vue-app
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: vue-app
